### ISSUE TITLE
Unable to use services

### ISSUE THREAD

**Issue by Karrq** [zhaofengli/nix-homebrew#13]
I tried enabling emacs-plus' service, but an error occurs when the service is configured.

```
setting up user launchd services...
Homebrew bundle...
Using emacs-plus
Error: cannot load such file -- /Homebrew/service
/nix/store/ys4kqcgld76ys01x4m6czj2l7kbn66f8-source/lib/service/formula_wrapper.rb:206:in `require_relative'
/nix/store/ys4kqcgld76ys01x4m6czj2l7kbn66f8-source/lib/service/formula_wrapper.rb:206:in `load_service'
/nix/store/ys4kqcgld76ys01x4m6czj2l7kbn66f8-source/lib/service/formula_wrapper.rb:67:in `service_startup?'
/nix/store/ys4kqcgld76ys01x4m6czj2l7kbn66f8-source/lib/service/services_cli.rb:280:in `service_load'
/nix/store/ys4kqcgld76ys01x4m6czj2l7kbn66f8-source/lib/service/services_cli.rb:122:in `block in start'
/nix/store/ys4kqcgld76ys01x4m6czj2l7kbn66f8-source/lib/service/services_cli.rb:97:in `each'
/nix/store/ys4kqcgld76ys01x4m6czj2l7kbn66f8-source/lib/service/services_cli.rb:97:in `start'
/nix/store/ys4kqcgld76ys01x4m6czj2l7kbn66f8-source/lib/service/commands/restart.rb:31:in `run'
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:126:in `services'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

I have the same error when just using `brew services` to list the available services

**Comment by gshpychka** [comment]
You need to add the `homebrew/homebrew-services` tap manually.

**Comment by gshpychka** [comment]
What about your `nix-darwin.homebrew.taps`?

**Comment by Karrq** [comment]
That's left null actually - I had an issue before when I tried specifying my taps there...

**Comment by gshpychka** [comment]
Try this, maybe it will help: https://github.com/gshpychka/dotfiles/blob/436e5e6399878b2c65d736d0a99ccdf3fb6d7a5b/machines/eve/homebrew.nix#L9

**Comment by Karrq** [comment]
Well that didn't cause issue like I saw before, but I still can't use `brew services`

**Comment by Karrq** [comment]
Same error as before...

**Comment by harrygallagher4** [comment]
This is due to `brew services` using ruby's `require_relative`.

[Homebrew/homebrew-services/lib/service/formula_wrapper.rb:204](https://github.com/Homebrew/homebrew-services/blob/a87be049dad97622c8382f09f5662595607dc498/lib/service/formula_wrapper.rb#L204)

```ruby
# The purpose of this function is to lazy load the Homebrew::Service class
# and avoid nameclashes with the current Service module.
# It should be used instead of calling formula.service directly.
def load_service
  require_relative "../../../../../Homebrew/service"

  formula.service
end
```

The file it's looking for is `/opt/homebrew/Library/Homebrew/service.rb` but when taps are in the Nix store it resolves to `/nix/store/Homebrew/service.rb`. Using `require_relative` seems like bad practice although I know next to nothing about ruby. I just edited the file and changed it to `require_relative "/opt/homebrew/Library/Homebrew/service"` to see if that worked and it did.

I have no idea how to implement a real fix.

**Comment by harrygallagher4** [comment]
Okay, this feels like an absolutely ridiculous way to fix this, but I ended up applying a patch to the homebrew-services flake input. I'll include the patch and an abridged version of my configuration.


```diff
--- a/lib/service/formula_wrapper.rb	2024-06-08 17:48:09.693241764 -0500
+++ b/lib/service/formula_wrapper.rb	2024-06-08 17:49:08.262498938 -0500
@@ -201,7 +201,7 @@
     # and avoid nameclashes with the current Service module.
     # It should be used instead of calling formula.service directly.
     def load_service
-      require_relative "../../../../../Homebrew/service"
+      require_relative "/opt/homebrew/Library/Homebrew/service"
 
       formula.service
     end
```

In the flake inputs:
```nix
homebrew-services = {
  url = "github:homebrew/homebrew-services";
  flake = false;
};
```

In the outputs:
```nix
darwinConfigurations = nixpkgs.lib.genAttrs darwinSystems (
  system: let
    user = "harry";
    homebrew-services-patched = nixpkgs.legacyPackages."${system}".applyPatches {
      name = "homebrew-services-patched";
      src = homebrew-services;
      patches = [./homebrew-services.patch];
    };
  in
    darwin.lib.darwinSystem {
      modules = [
        nix-homebrew.darwinModules.nix-homebrew
        {
          nix-homebrew = {
            inherit user;
            enable = true;
            taps = {
              "homebrew/homebrew-core" = homebrew-core;
              "homebrew/homebrew-cask" = homebrew-cask;
              "homebrew/homebrew-bundle" = homebrew-bundle;
              "homebrew/homebrew-services" = homebrew-services-patched;
            };
            mutableTaps = false;
            autoMigrate = true;
          };
        }
      ];
    }
);
```

Obviously I have removed a lot of my configuration just to shorten things but you get the gist of it.

**Comment by Karrq** [comment]
Can confirm applying this patch fixes my issue <3 Thanks @harrygallagher4!

**Comment by b4lisong** [comment]
Also confirming @harrygallagher4's patch fixes the issue.

For Intel Macs, the path is `/usr/local/Homebrew/Library/Homebrew/service` instead of `/opt/homebrew/Library/Homebrew/service`

```diff
--- a/lib/service/formula_wrapper.rb	2024-06-08 17:48:09.693241764 -0500
+++ b/lib/service/formula_wrapper.rb	2024-06-08 17:49:08.262498938 -0500
@@ -201,7 +201,7 @@
     # and avoid nameclashes with the current Service module.
     # It should be used instead of calling formula.service directly.
     def load_service
-      require_relative "../../../../../Homebrew/service"
+      require_relative "/usr/local/Homebrew/Library/Homebrew/service"
 
       formula.service
     end
```

Thanks for the workaround!

**Comment by pmithunish** [comment]
I am new to nix and it's ecosystem.

Thanks to all the authors, contributors, maintainers and the community for the awesome work you do.

Don't know if the following might help someone and please ignore if this is pretty straightforward and comes under basic understanding.

Thanks @harrygallagher4 and @b4lisong for your solution.

It didn't worked for me initially because I saw in the recent `flake.nix` based on the `nix-darwin` starter configuration there are few changes in the syntax and stuff.

I was able to make it work for me with the following changes.

```nix
{
  description = "My Darwin system flake";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    nix-darwin.url = "github:LnL7/nix-darwin";
    nix-darwin.inputs.nixpkgs.follows = "nixpkgs";
    nix-homebrew.url = "github:zhaofengli-wip/nix-homebrew";

    homebrew-bundle = {
      url = "github:homebrew/homebrew-bundle";
      flake = false;
    };
    homebrew-core = {
      url = "github:homebrew/homebrew-core";
      flake = false;
    };
    homebrew-cask = {
      url = "github:homebrew/homebrew-cask";
      flake = false;
    };
    homebrew-services = {
      url = "github:homebrew/homebrew-services";
      flake = false;
    };
    homebrew-FelixKratz-formulae = {
      url = "github:FelixKratz/homebrew-formulae";
      flake = false;
    };
  };

  outputs =
    inputs@{
      self,
      nix-darwin,
      nixpkgs,
      nix-homebrew,
      homebrew-bundle,
      homebrew-core,
      homebrew-cask,
      homebrew-services,
      homebrew-FelixKratz-formulae,
    }:
    let
      hostPlatform = "aarch64-darwin";
      configuration =
        {
          pkgs,
          lib,
          nix-homebrew,
          homebrew-bundle,
          homebrew-core,
          homebrew-cask,
          homebrew-services,
          homebrew-FelixKratz-formulae,
          ...
        }:
        {
          homebrew = {
            enable = true;
            onActivation.autoUpdate = true;
            onActivation.upgrade = true;
            onActivation.cleanup = "zap";
            brews = [
              {
                name = "FelixKratz/formulae/svim";
                start_service = true;
              }
            ];
          };
          nixpkgs.hostPlatform = hostPlatform;
        };
      homebrew-services-patched = nixpkgs.legacyPackages."${hostPlatform}".applyPatches {
        name = "homebrew-services-patched";
        src = homebrew-services;
        patches = [ ./homebrew-services.patch ];
      };
    in
    {
      darwinConfigurations."apple" = nix-darwin.lib.darwinSystem {
        modules = [
          (
            { config, ... }:
            {
              homebrew.taps = builtins.attrNames config.nix-homebrew.taps;
            }
          )
          configuration
          nix-homebrew.darwinModules.nix-homebrew
          {
            nix-homebrew = {
              enable = true;
              enableRosetta = true;
              user = "apple";
              taps = {
                "homebrew/homebrew-bundle" = homebrew-bundle;
                "homebrew/homebrew-core" = homebrew-core;
                "homebrew/homebrew-cask" = homebrew-cask;
                "homebrew/homebrew-services" = homebrew-services-patched;
                "FelixKratz/homebrew-formulae" = homebrew-FelixKratz-formulae;
              };
              mutableTaps = false;
              autoMigrate = true;
            };
          }
        ];
      };
      darwinPackages = self.darwinConfigurations."apple".pkgs;
    };
}
```

In the above configuration the following is the main code chuck to focus on.
```nix
homebrew-services-patched = nixpkgs.legacyPackages."${hostPlatform}".applyPatches {
  name = "homebrew-services-patched";
  src = homebrew-services;
  patches = [ ./homebrew-services.patch ];
};
```

Remember to define the `hostPlatform` using the following code.
```nix
hostPlatform = "aarch64-darwin";
```

**Comment by belizariogr** [comment]
I cant apply this patch... Im getting the following error:

```
error (ignored): error: end of string reached
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'darwin-system-25.05.20241204.2f9d395+darwin5.a35b08d'
         whose name attribute is located at /nix/store/ri2aw0dp8gjpygcx2q1ib5ajh85gc0f0-source/pkgs/stdenv/generic/make-derivation.nix:336:7

       … while evaluating attribute 'activationUserScript' of derivation 'darwin-system-25.05.20241204.2f9d395+darwin5.a35b08d'
         at /nix/store/9w5mmnkypiqczdlvmc4l2hd4xc3m44bq-source/modules/system/default.nix:98:7:
           97|       activationScript = cfg.activationScripts.script.text;
           98|       activationUserScript = cfg.activationScripts.userScript.text;
             |       ^
           99|       inherit (cfg) darwinLabel;

       … while evaluating the option `system.activationScripts.userScript.text':

       … while evaluating definitions from `/nix/store/9w5mmnkypiqczdlvmc4l2hd4xc3m44bq-source/modules/system/activation-scripts.nix':

       … while evaluating the option `system.activationScripts.extraUserActivation.text':

       … while evaluating the option `system.activationScripts.setup-homebrew.text':

       … while evaluating definitions from `/nix/store/8jxy9fzigmlk08b97djj9ld6qz60wfxy-source/modules':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: path '/nix/store/6zpkv1ywamm05jf5yc1s2lnkq8hni239-source/homebrew-services.patch' does not exist

``` 

thats my flake.nix

```nix
{
    description = "Belizário nix-darwin system flake";

    inputs = {
        nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
        nix-darwin.url = "github:LnL7/nix-darwin";
        nix-darwin.inputs.nixpkgs.follows = "nixpkgs";
        nix-homebrew.url = "github:zhaofengli-wip/nix-homebrew";

        # Optional: Declarative tap management
        homebrew-core = {
            url = "github:homebrew/homebrew-core";
            flake = false;
        };
        homebrew-cask = {
            url = "github:homebrew/homebrew-cask";
            flake = false;
        };
        homebrew-bundle = {
            url = "github:homebrew/homebrew-bundle";
            flake = false;
        };       
        homebrew-services = {
            url = "github:homebrew/homebrew-services";
            flake = false;
        };
    };

    outputs = inputs@{ self, nix-darwin, nixpkgs, 
        nix-homebrew,
        homebrew-bundle,
        homebrew-core,
        homebrew-cask,
        homebrew-services 
    }:
    let
    hostPlatform = "aarch64-darwin";
    homebrew-services-patched = nixpkgs.legacyPackages."${hostPlatform}".applyPatches {
        name = "homebrew-services-patched";
        src = homebrew-services;
        patches = [ ./homebrew-services.patch ];
    };
    configuration = { 
            pkgs, config, 
            homebrew-bundle,
            homebrew-core,
            homebrew-cask,
            homebrew-services,
            ... 
    }: 
    {
        nixpkgs.config.allowUnfree = true;
        
        environment.systemPackages = [
            pkgs.mkalias
            pkgs.vscode
            pkgs.nodejs_20
            pkgs.google-chrome
        ];

        homebrew = {
            enable = true;

            caskArgs.no_quarantine = true;

            brews = [
                "mas"
                "zsh-syntax-highlighting"
                {
                    name = "mariadb@11.4";
                    link = true;
                    # start_service = true;
                    conflicts_with = [ 
                        "mariadb" 
                        "mysql" 
                    ];
                }
                {
                    name = "redis";
                    start_service = true;
                }
            ];

            casks = [
                "sublime-text"
                "iina"
                "the-unarchiver"
                "scroll-reverser"
                "iterm2"
                "docker"
            ];

            masApps = {
                "Action" = 1322446807;
                "Proton Pass For Safari" = 6502835663;
                "New Terminal Here" = 1067646949;
                "WhatsApp" = 310633997;
                "xcode" = 497799835;
            };

            onActivation.cleanup = "zap";
            onActivation.autoUpdate = true;
            onActivation.upgrade = true;                
        };

        # Fonts
        fonts.packages = [
            pkgs.fira-code
            pkgs.nerd-fonts.jetbrains-mono
        ];

        system.activationScripts.applications.text = let
        
        env = pkgs.buildEnv {
            name = "system-applications";
            paths = config.environment.systemPackages;
            pathsToLink = "/Applications";
        };

        in
            pkgs.lib.mkForce ''
            
            '';

        system.defaults = {

            NSGlobalDomain = {
                AppleICUForce24HourTime = true;
                AppleInterfaceStyle = "Dark";
                AppleInterfaceStyleSwitchesAutomatically = false;
                AppleSpacesSwitchOnActivate = true;
                KeyRepeat = 2;
                "com.apple.keyboard.fnState" = true;
            };

            trackpad.Clicking = true;

            controlcenter = {
                BatteryShowPercentage = true;
                Sound = true;
            };

            dock = {
                mineffect = "scale";
                minimize-to-application = true;
                show-recents = false;
                # persistent-apps = [ ];
                # persistent-others = [];
                tilesize = 48;
            };

            finder = {
                FXPreferredViewStyle = "Nlsv";
                NewWindowTarget = "Home";
                ShowHardDrivesOnDesktop = true;
                ShowMountedServersOnDesktop = true;
                ShowPathbar = true;
                _FXSortFoldersFirst = true;
            };

            loginwindow = {
                GuestEnabled = false;
            };
        };

        networking = {
            knownNetworkServices = [
                "Wi-Fi"
                "Ethernet Adaptor"
                "Thunderbolt Ethernet"
            ];
            dns = [
                "1.1.1.1"
                "8.8.8.8"
                "8.8.4.4"
            ];
        };
        
        services.redis.enable = true;

        # Necessary for using flakes on this system.
        nix.settings.experimental-features = "nix-command flakes";

        # Enable alternative shell support in nix-darwin.
        # programs.fish.enable = true;

        # Set Git commit hash for darwin-version.
        system.configurationRevision = self.rev or self.dirtyRev or null;

        # Used for backwards compatibility, please read the changelog before changing.
        # $ darwin-rebuild changelog
        system.stateVersion = 5;

        # The platform the configuration will be used on.
        nixpkgs.hostPlatform = "${hostPlatform}";
    };

    in 
    {
        # Build darwin flake using:
        # $ darwin-rebuild build --flake .#simple        

        darwinConfigurations."belizario" = nix-darwin.lib.darwinSystem {            
            modules = [
                (
                    { config, ... }:
                    {
                        homebrew.taps = builtins.attrNames config.nix-homebrew.taps;
                    }
                )
                configuration
                nix-homebrew.darwinModules.nix-homebrew  {

                    nix-homebrew = {
                        # Install Homebrew under the default prefix
                        enable = true;

                        # Apple Silicon Only: Also install Homebrew under the default Intel prefix for Rosetta 2
                        enableRosetta = true;

                        # User owning the Homebrew prefix
                        user = "belizario";

                        taps = {
                            "homebrew/homebrew-core" = homebrew-core;
                            "homebrew/homebrew-cask" = homebrew-cask;
                            "homebrew/homebrew-bundle" = homebrew-bundle;
                            "homebrew/homebrew-services" = homebrew-services-patched;       
                        };

                        mutableTaps = false;
                        autoMigrate = true;
                    };
                }
            ];
        };

        # Expose the package set
        darwinPackages = self.darwinConfigurations."belizario".pkgs;
    };
}

``` 
Does someone know how to fix?

**Comment by zhaofengli** [comment]
You need to first place the patch there as `homebrew-services.patch` and then `git add` it so it's tracked by git (otherwise it's not part of the flake).

**Comment by belizariogr** [comment]
Ok, but, where is the patch? Where can I get it?

**Comment by belizariogr** [comment]
Ok, nevermind... I was not creating the .patch file alonside flake.nix. Thanks

**Comment by ed9w2in6** [comment]
Hi guys!  It seems that `homebrew-services` is now deprecated:
https://github.com/Homebrew/homebrew-services/tree/master

and the migrated function now won't do require-relative anymore:

https://github.com/Homebrew/brew/blob/9bca39d89cf6bb2b817ef6dfe0c3a6f25fb3d1ad/Library/Homebrew/services/formula_wrapper.rb#L232-L240

Is this fixed?  I don't use `homebrew-services` so I don't know.

**Comment by Karrq** [comment]
I actually updated my config the other day and was notified that the patch wasn’t applied anymore, so I removed it and the system worked anyways, so I think it’s okay, but at the same time I don’t actively use any brew service as I moved away from what I was using, so I’d wait for a comment from someone that actually uses a service
