### ISSUE TITLE
`brew livecheck` fails to install bundler gems

### ISSUE THREAD

**Issue by ian-h-chamberlain** [zhaofengli/nix-homebrew#35]
I suppose this is kind of expected, since normally `brew` installs its own dependencies when running some development commands for the first time, but is not allowed to modify the nix store:

```console
$ brew livecheck --debug kde-mac/kde/kdeconnect
Error: Permission denied @ rb_sysopen - /nix/store/v19ip7y08262kadi01g4wnrr8cxd9qbx-brew-4.3.5-patched/Library/Homebrew/vendor/bundle/ruby/3.3.0/.homebrew_vendor_version
Warning: Removed Sorbet lines from backtrace!
Rerun with `--verbose` to see the original backtrace
/nix/store/v19ip7y08262kadi01g4wnrr8cxd9qbx-brew-4.3.5-patched/Library/Homebrew/utils/gems.rb:296:in `write'
/nix/store/v19ip7y08262kadi01g4wnrr8cxd9qbx-brew-4.3.5-patched/Library/Homebrew/utils/gems.rb:296:in `write'
/nix/store/v19ip7y08262kadi01g4wnrr8cxd9qbx-brew-4.3.5-patched/Library/Homebrew/utils/gems.rb:296:in `install_bundler_gems!'
/nix/store/v19ip7y08262kadi01g4wnrr8cxd9qbx-brew-4.3.5-patched/Library/Homebrew/dev-cmd/livecheck.rb:52:in `run'
/opt/homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

Is there some workaround I can use to either 
- preinstall the necessary dependencies in the patched brew (maybe a new `nix-homebrew.setupCommands` or something that can run some commands to install gems?)
- tell `brew` to install in some other location, or give it a mutable directory to install stuff to?

**Comment by zhaofengli** [comment]
Well, this is tricky... I think the second way sounds nicer, but I don't have a strong opinion on this.

For reference, we patch Brew to use the bundled gems from upstream with a Nix-managed Ruby interpreter here: https://github.com/zhaofengli/nix-homebrew/commit/e88b940e4ca15127991eb8095c56db40a55e457f
